name = "space"
workers_dev = false
main = "src/index.ts"
compatibility_date = "2022-04-27"
account_id = "2db2112b269ed3616ed3a863a222f3e8"

[env.ipfs-bucket]
name = "ipfs-bucket"
workers_dev = false
main = "src/ipfs-bucket.ts"
route = { pattern = "https://cdn.digitalclouds.dev/ipfs/*", zone_id = "7600c132f040aea60b0533ad801986d5" }
