name = "space"
workers_dev = true
main = "src/index.ts"
account_id = "2db2112b269ed3616ed3a863a222f3e8"

[env.ipfs-bucket]
name = "ipfs-bucket"
workers_dev = true
main = "src/ipfs-bucket.ts"
tsconfig = "./tsconfig.json"

#[[r2_buckets]]
#inding = "R2_STORE"
#bucket_name = "r2-store"

[env]
compatibility_date = "2022-09-28"
compatibility_flags = ["formdata_parser_supports_files"]
