compatibility_date = "2022-02-15"
name = "space"
type = "javascript"
account_id = "2db2112b269ed3616ed3a863a222f3e8"
zone_id = "7600c132f040aea60b0533ad801986d5"
workers_dev = false
usage_model = 'unbound'
routes = ["cdn.digitalclouds.dev/*"]
