name: "🔵 GCP Action"

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths: [gcs/**, .github/workflows/gcp-action.yml]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job_id:
    name: "🆙 GCP"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bucket: [digital-space, gcp-space]
      fail-fast: false
    permissions:
      contents: "read"
      id-token: "write"
    timeout-minutes: 15
    environment: google-cloud
    if: github.repository == 'digital-clouds/space'
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - id: "auth"
        uses: google-github-actions/auth@8254fb75a33b976a221574d287e93919e6a36f70 # v2
        with:
          workload_identity_provider: "${{ secrets.DIGITAL_CLOUDS_PROVIDER }}"
          service_account: "${{ secrets.DIGITAL_CLOUDS_SERVICE }}"
      - if: startsWith(matrix.bucket, 'digital-space')
        name: "📤 digital-space"
        id: "upload-digital-space"
        uses: "google-github-actions/upload-cloud-storage@22121cd842b0d185e042e28d969925b538c33d77" # v2
        with:
          path: "gcs/63ab8820-bc9f-43aa-9045-801ac5af4bb6"
          destination: "digital-space"
      - if: startsWith(matrix.bucket, 'gcp-space')
        name: "📤 gcp-space"
        id: "upload-gcp-space"
        uses: "google-github-actions/upload-cloud-storage@22121cd842b0d185e042e28d969925b538c33d77" # v2
        with:
          path: "gcs/2d8aa135-97c0-4ab1-8443-2eafcec4055e"
          destination: "gcp-space"

      # https://github.com/google-github-actions/setup-gcloud#cloud-sdk-inputs
      #- name: 'Google Cloud SDK'
      #  id: 'setup-gcloud'
      #  uses: 'google-github-actions/setup-gcloud@v0'
      #- name: 'gcloud CLI'
      #  run: 'gcloud info'
