---
name: '🤠 Wrangler'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  wrangler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: '🤠 Run >>'
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        workingDirectory: '.'
