---
name: "🔄 Rclone Action"

on:
  push:
    branches: [main]
    paths:
      - "r2/**"
  workflow_dispatch: {}

jobs:
  sync:
    if: github.repository == 'digital-clouds/space'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      local_path: "./r2"
      remote_path: "r2:space"
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: "⏫ Run rclone"
        uses: digital-clouds/rclone-action@main
        with:
          config: ${{ secrets.R2_RCLONE_CONFIG }}
          args: "copy -M ${{ env.local_path }} ${{ env.remote_path }}"
          debug: false
