name: '🔵 Upload to GCS'

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths: [upload/**, .github/workflows/upload-to-gcs.yml]

jobs:
  job_id:
    name: '🆙 Upload'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/410787283689/locations/global/workloadIdentityPools/id-pool/providers/id-provider'
          service_account: 'gcp-account@digital-clouds.iam.gserviceaccount.com'

      - id: 'upload-digital-space'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'upload/digital-space/assets'
          destination: 'digital-space'

      - id: 'upload-gcp-space'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'upload/gcp-space/assets'
          destination: 'gcp-space'

#      - id: 'uploaded-files'
#        uses: 'digital-clouds/space@main'
#        env:
#          files: '${{ steps.upload-digital-space.outputs.uploaded }}'
