---
name: '🤠 Wrangler Action'

on:
  push:
    branches: [main]
    paths: [workers/**]
  schedule:
    - cron: '0 02 * * */2'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to: <dev|staging|prod>'
        default: 'prod'
        required: true

jobs:
  deploy:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: production
    if: github.repository == 'digital-clouds/space'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: '🤠 Digital Space'
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'workers/digital-space'
          command: deploy
      - name: '🤠 GCP Space'
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'workers/gcp-space'
          command: deploy
